name: Quarto Python Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: quarto-python
        environment-file: environment.yml
      
    - name: Quarto report
      run: quarto render reports/qmd_example.qmd --to html
      
    - name: HTML report
      uses: actions/upload-artifact@v2
      with:
        name: quarto-html-report
        path: reports/qmd_example.html
